# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/Cocos/Creator/3.8.3/CocosCreator.app/Contents/Resources/resources/3d/engine/native/external/sources/boost-source/container/CMakeLists.txt))

/Users/kemal/Desktop/PistiReal/build/ios/proj/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/Cocos/Creator/3.8.3/CocosCreator.app/Contents/Resources/tools/cmake/bin/cmake -H/Users/kemal/Desktop/PistiReal/native/engine/ios -B/Users/kemal/Desktop/PistiReal/build/ios/proj
